/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArticleSection = "Business" | "Caribbean" | "Culture" | "Local" | "Opinion" | "Tech" | "World";

export type ArticleStatus = "draft" | "published" | "review" | "scheduled";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type NewsroomRole = "editor" | "owner" | "writer";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface Articles {
  aiMetadata: Generated<import('./aiDraftPolicy').AiDraftMetadata | null>;
  authorId: number | null;
  body: Generated<string>;
  byline: string;
  createdAt: Generated<Timestamp>;
  excerpt: Generated<string>;
  featured: Generated<boolean>;
  id: Generated<number>;
  publishedAt: Timestamp | null;
  section: ArticleSection;
  slug: string;
  sourceId: number | null;
  sourceUrl: string | null;
  status: Generated<ArticleStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AuditLog {
  action: string;
  articleId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  userId: number | null;
}

export interface Invitations {
  email: string | null;
  expiresAt: Timestamp;
  id: Generated<number>;
  role: NewsroomRole;
  tokenHash: string;
  usedAt: Timestamp | null;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Sources {
  checkedAt: Timestamp | null;
  enabled: Generated<boolean>;
  feedUrl: string | null;
  id: Generated<number>;
  lastError: string | null;
  lastSuccessAt: Timestamp | null;
  name: string;
  rightsNote: string;
  section: ArticleSection;
  website: string;
}

export interface TeamMembers {
  role: NewsroomRole;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface AiDraftRuns {
  period: string; category: string; status: Generated<string>; attempts: Generated<number>;
  articleId: number | null; topic: string | null; sourceUrls: Generated<string[]>;
  error: string | null; startedAt: Generated<Timestamp>; finishedAt: Timestamp | null;
}
export interface DB {
  aiDraftRuns: AiDraftRuns;
  articles: Articles;
  auditLog: AuditLog;
  invitations: Invitations;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  sources: Sources;
  teamMembers: TeamMembers;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const NewsroomRoleArrayValues: [NewsroomRole, ...NewsroomRole[]] = ["editor","owner","writer"];
export const ArticleStatusArrayValues: [ArticleStatus, ...ArticleStatus[]] = ["draft","published","review","scheduled"];
export const ArticleSectionArrayValues: [ArticleSection, ...ArticleSection[]] = ["Business","Caribbean","Culture","Local","Opinion","Tech","World"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
