"use client";
import React,{useState} from 'react';
import {Link,useSearchParams} from "@/newsroom/navigation";
import {useQuery} from '@tanstack/react-query';
import {getNews} from '../endpoints/news_GET.schema';
import {StoryCard} from '../components/StoryCard';
import {Helmet} from "@/newsroom/Helmet";
import {Search,ArrowUpRight,ArrowRight} from 'lucide-react';
import {Input} from '../components/Input';
import {Button} from '../components/Button';
import s from './_index.module.css';
export default function Home(){
const [params,setParams]=useSearchParams();const section=params.get('section')||'Local';const search=params.get('q')||'';const sourceFilter=params.get('source')||'all';const [count,setCount]=useState(12);const setSection=(x:string)=>{setParams({section:x});setCount(12)};const setSearch=(x:string)=>{const p=new URLSearchParams(params);p.set('q',x);setParams(p,{replace:true});setCount(12)};const q=useQuery({queryKey:['news'],queryFn:getNews});const filtered=(q.data?.articles||[]).filter(a=>a.section===section&&(sourceFilter==='all'||String(a.sourceId||'original')===sourceFilter)&&(!search||(a.title+' '+a.excerpt+' '+a.byline+' '+(a.sourceName||'Lyniq')).toLowerCase().includes(search.toLowerCase())));const buckets=new Map<string,typeof filtered>();for(const a of filtered){const key=a.sourceName?.startsWith('Global Voices')?'Global Voices':a.sourceName||'Lyniq';buckets.set(key,[...(buckets.get(key)||[]),a])}const stories:typeof filtered=[];while([...buckets.values()].some(b=>b.length)){for(const b of buckets.values()){const a=b.shift();if(a)stories.push(a)}}
return <div className={s.page}><Helmet><title>Lyniq | Trinidad & Tobago, in perspective</title><link rel="canonical" href={'https://lyniq.net/'+(section!=='Local'?'?section='+section:'')}/><meta property="og:title" content="Lyniq | Trinidad & Tobago, in perspective"/><meta name="description" content="Trinidad and Tobago news, original journalism and perspectives from across the Caribbean and the world."/></Helmet>
<div className={s.top}><span>TRINIDAD & TOBAGO · INDEPENDENT PERSPECTIVES</span><Link to="/admin">Newsroom sign in ↗</Link></div>
<header className={s.mast}><div><span className={s.flag}/><span>Two islands.<br/>A wider perspective.</span></div><Link to="/" className={s.logo}>lyniq<span>.</span></Link><span>THE NEWS, CONNECTED<br/><b>Port of Spain · Scarborough</b></span></header>
<nav className={s.nav}>{['Local','Caribbean','World','Business','Tech','Culture','Opinion'].map(x=><Button variant="ghost" key={x} onClick={()=>setSection(x)} className={section===x?s.active:''}>{x==='Local'?'Trinidad & Tobago':x}</Button>)}<a href="#search"><Search size={19}/><span className={s.sr}>Search</span></a></nav>
<main><div className={s.line}><span>THE LATEST</span><p>A wider view starts with more than one source.</p><Link to="/about">Our editorial approach <ArrowRight size={16}/></Link></div>
<div className={s.section}><h1>{section==='Local'?'Trinidad & Tobago':section}</h1><span>HOME FIRST. WORLD ALWAYS.</span></div>
<div className={s.lead}><article><figure style={{margin:0}}><img src="/images/trinidad-editorial.png" alt="Red, black and white editorial illustration of a scarlet ibis over mangroves" width="1024" height="576" style={{width:'100%',height:'auto',display:'block'}}/><figcaption style={{fontSize:12,color:'var(--muted-foreground)',marginTop:6}}>Trinidad, in print · AI-assisted editorial illustration</figcaption></figure>{stories[0]?<StoryCard article={stories[0]} lead/>:<><p className={s.label}>THE LYNIQ BRIEF</p><h2>Your islands. Your world.<br/>More than one perspective.</h2><p>{q.isFetching?'Loading the latest edition…':'No stories match this selection yet. Explore the source directory or another section.'}</p><Link to="/sources">Explore our sources →</Link></>}</article>
<aside><p className={s.label}>ACROSS THE NEWSROOMS</p>{[{name:'Trinidad Guardian',url:'https://www.guardian.co.tt/',title:'Explore the latest reporting from the Trinidad Guardian'},{name:'Trinidad Express',url:'https://trinidadexpress.com/',title:'Read the national conversation at the Trinidad Express'},{name:'Wired868',url:'https://wired868.com/',title:'Sport, society and independent commentary'}].map(x=><article key={x.name}><span>{x.name} · Source directory</span><h3><a href={x.url} target="_blank" rel="noopener noreferrer">{x.title} <ArrowUpRight size={18}/></a></h3></article>)}<Link to="/sources">View all sources →</Link></aside></div>
<div className={s.section} id="search"><h2>The news desk</h2><div className={s.search}><Search size={18}/><Input aria-label="Search articles" placeholder="Search stories, topics or sources" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className={s.filters}><Button variant={sourceFilter==='all'?'primary':'outline'} onClick={()=>{const p=new URLSearchParams(params);p.delete('source');setParams(p)}}>All sources</Button>{[...new Map((q.data?.articles||[]).filter(a=>a.section===section).map(a=>[String(a.sourceId||'original'),a.sourceName||'Lyniq originals'])).entries()].map(([id,name])=><Button size="sm" key={id} variant={sourceFilter===id?'primary':'outline'} onClick={()=>{const p=new URLSearchParams(params);p.set('source',id);setParams(p);setCount(12)}}>{name}</Button>)}</div>{q.isError?<div role="alert" className={s.empty}>{q.error.message}<Button onClick={()=>q.refetch()}>Try again</Button></div>:q.isFetching&&!q.data?<div className={s.empty}>Loading stories…</div>:stories.length?<><div className={s.cards}>{stories.slice(0,count).map(a=><StoryCard key={a.id} article={a}/>)}</div>{count<stories.length&&<Button variant="outline" onClick={()=>setCount(count+12)}>Show more stories</Button>}</>:<div className={s.empty}>No stories match your filters. Try a different section, source or search.</div>}<p style={{fontSize:13,color:'var(--muted-foreground)'}}>Feed coverage is currently limited. Publisher rotation supports variety; it does not guarantee political balance. <Link to="/sources">See source availability and our method.</Link></p>
<div className={s.newsletter}><div><span className={s.label}>THE LYNIQ LETTER</span><h2>A little perspective.<br/>Straight to your inbox.</h2><p>Our newsletter is in the works. Come back for signup details.</p></div><span className={s.newsmark}>l.</span></div>
</main><footer><Link to="/" className={s.logo}>lyniq<span>.</span></Link><p>Trinidad & Tobago at the centre. The world in view.</p><div>{['About','Sources','Community','Privacy','Terms'].map(x=><Link key={x} to={'/'+x.toLowerCase()}>{x}</Link>)}<Link to="/admin">Newsroom</Link></div><small>© {new Date().getFullYear()} Lyniq. Original publishers retain rights to their work.</small></footer></div>
}

