import {schema} from './editor_POST.schema';import {db} from '../helpers/db';import {newsroomAccess} from '../helpers/newsroomAccess';import {importFeeds} from '../helpers/importFeeds';import {randomBytes,createHash} from 'crypto';import superjson from 'superjson';import {sql} from 'kysely';
export async function handle(request:Request){let user;try{user=await newsroomAccess(request)}catch{return new Response(superjson.stringify({error:'Newsroom access required'}),{status:403})}try{const d=schema.parse(superjson.parse(await request.text()));const role=user.newsroomRole;
if(d.action==='save'){if(role==='writer'&&!['draft','review'].includes(d.status))throw new Error('Only editors can publish or schedule');const prior=d.id?await db.selectFrom('articles').selectAll().where('id','=',d.id).executeTakeFirst():null;if(d.id&&!prior)throw new Error('Article not found');if(prior?.sourceId)throw new Error('Imported stories cannot be rewritten');if(role==='writer'&&prior&&(prior.authorId!==user.id||['published','scheduled'].includes(prior.status)))throw new Error('An editor must change published stories');if(['published','scheduled'].includes(d.status)&&d.body.trim().length<30)throw new Error('Add article text before publication');let publishedAt=d.publishedAt?new Date(d.publishedAt):null;if(d.status==='scheduled'&&(!publishedAt||publishedAt.getTime()<=Date.now()))throw new Error('Choose a future publication time');if(d.status==='published')publishedAt=prior?.publishedAt&&prior.publishedAt<=new Date()?prior.publishedAt:new Date();
const values={title:d.title,excerpt:d.excerpt,body:d.body,section:d.section,status:d.status,publishedAt,featured:role==='writer'?false:d.featured,updatedAt:new Date()};
await db.transaction().execute(async trx=>{let id=d.id;if(id){const updated=await trx.updateTable('articles').set({...values,version:sql<number>`version + 1`}).where('id','=',id).where('version','=',d.version??0).returning('id').executeTakeFirst();if(!updated)throw new Error('Another editor changed this article. Reload before saving.')}else{const slug=d.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,80).replace(/^-|-$/g,'')+'-'+randomBytes(4).toString('hex');id=(await trx.insertInto('articles').values({...values,slug,authorId:user.id,byline:user.displayName}).returning('id').executeTakeFirstOrThrow()).id;}await trx.insertInto('auditLog').values({userId:user.id,articleId:id,action:'article:'+d.status}).execute();});}
else if(d.action==='invite'){if(role!=='owner')throw new Error('Owner access required');const token=randomBytes(32).toString('hex');await db.insertInto('invitations').values({tokenHash:createHash('sha256').update(token).digest('hex'),email:d.email,role:d.role,expiresAt:new Date(Date.now()+7*86400000)}).execute();return new Response(superjson.stringify({ok:true,invitation:'/newsroom/join#'+token}),{headers:{'Cache-Control':'no-store'}});}
else if(d.action==='role'){if(role!=='owner')throw new Error('Owner access required');const target=await db.selectFrom('teamMembers').selectAll().where('userId','=',d.userId).executeTakeFirst();if(!target||target.role==='owner')throw new Error('Owner membership cannot be changed');await db.transaction().execute(async trx=>{if(d.role==='remove')await trx.deleteFrom('teamMembers').where('userId','=',d.userId).execute();else await trx.updateTable('teamMembers').set({role:d.role}).where('userId','=',d.userId).execute();await trx.deleteFrom('sessions').where('userId','=',d.userId).execute();});}
else if(d.action==='source'){if(role!=='owner')throw new Error('Owner access required');await db.updateTable('sources').set({enabled:d.enabled,rightsNote:d.rightsNote}).where('id','=',d.id).execute();}
else {if(role==='writer')throw new Error('Editor access required');await importFeeds();}
return new Response(superjson.stringify({ok:true}));}catch(e){return new Response(superjson.stringify({error:e instanceof Error?e.message:'Action failed'}),{status:400})}}
